# Generated by Django 5.0.4 on 2024-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_jobpost_jobrequirement_jobpost_recruiter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobpostId', models.IntegerField(blank=True, null=True)),
                ('UserApplied', models.TextField(blank=True, null=True)),
                ('ApplyDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
