# Generated by Django 5.0.4 on 2024-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_jobapplication_jobpostid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='JobpostId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='UserApplied',
            field=models.TextField(blank=True, null=True),
        ),
    ]
