# Generated by Django 5.0.4 on 2024-05-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
