# Generated by Django 5.0.4 on 2024-05-04 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
