# Generated by Django 5.0.4 on 2024-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={},
        ),
        migrations.AlterModelManagers(
            name='recruiter',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
