# Generated by Django 5.0.4 on 2024-05-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_recruiters_delete_customuser'),
        ('dashboard', '0011_alter_jobpost_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
